{% set version = "7.3-20" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nnet/nnet_{{ version }}.tar.gz
  sha256: 8f33e17e0eb161cfbc1bfee4875baa23c66fcdba8215a64a63402b099db2b555

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('nnet')"           # [not win]
    - "\"%R%\" -e \"library('nnet')\""  # [win]

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2.0-or-later
  summary: Software for feed-forward neural networks with a single hidden layer, and for multinomial log-linear models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
