{% set version = "7.3-14" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nnet
  version: {{ version|replace("-", "_") }}

source:
  fn: nnet_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/nnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nnet/nnet_{{ version }}.tar.gz
  sha256: 5d1b9e9764d74d16c651f18f949aa4e9e2995ba64633cbfa2c6a7355ae30f4af

build:
  merge_build_host: true  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('nnet')"           # [not win]
    - "\"%R%\" -e \"library('nnet')\""  # [win]

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Software for feed-forward neural networks with a single hidden layer, and for multinomial log-linear models.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
