appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: AR8A5L2KWX7U3cmnlzrfEIKBAJVNLtlhzSqvcgQoO3nnI16eVbwcCu7oerE4yJi0L1OzMUPVp1QIATNqWRiPIQ4t/E6gUHAwGoR58SF/p0l+2uPHPFk6VPawdBe5mHYfu+0u5c7kN0Pp4xEIR7tAsfvhLCsrCnZEEDXDW8OF7rvW4wObr/6I5rUOB22tkLpkCbbUJ0Wuxj3OtNylKEcdN6DpSH1+kj46+uK338bgiUxBrGKE/vobmrpwiizyReZ5ecIT3e8L5prp7EDL6YuA3a9K4AHWf3CjXdRIxB0CoFK2P0b+2y5t6QIcRaTy4PgPCzmVWK5sWE5e40HlyRx5jFW8quv4R9dRN38cSKDQigBaI0xalrGaq+elLkuz/8Oa04sYY8NMURx/jjAM8VB2tnJmu7hZjQhRGpbi8gRTxOJjdwx2eu1QJaGMuD28UnhDNnoApMNYYZ2DMxMo39Gt4Movx3LKF4dhzQGxgp3UbUzxnDaY6vb7fGXW2ANhlyw1B0G9pgUYVm+OuiSPx2lhMPIsO100VS6OXU/gwKyZmEny1VgVppZ9l02ZDNC03ZZAfCwkuAlmxY6bZ/zlzszF8EkUXLnxnlBPR2Ac3j+DIJlHSlR9IHauUYWf36Z30mWbxWpqxos/2mFnf6uNnlITD10PNhWZT5amBsJL5jPtAZI=}
bot:
  automerge: true
